import type { UniversityProgram } from "./university-data"

export const universityPrograms: UniversityProgram[] = [
  // UNAM Programs
  {
    id: "unam-biochemistry",
    institution: "UNAM",
    faculty: "Faculty of Agriculture, Engineering & Natural Sciences",
    programName: "BSc in Biochemistry",
    programCode: "33BSBY",
    duration: "3 years",
    minPoints: 25,
    admissionRequirements: [
      { subject: "Biology", level: "NSSCAS", minGrade: "D" },
      { subject: "Chemistry", level: "NSSCAS", minGrade: "D" },
      { subject: "Mathematics", level: "NSSCO", minGrade: "C" },
      { subject: "English", level: "NSSCO", minGrade: "C" },
    ],
    careerPossibilities: ["Biochemist", "Lab Analyst", "Research Assistant"],
    interestCategories: ["Health & Medicine", "Science & Research"],
  },
  {
    id: "unam-microbiology",
    institution: "UNAM",
    faculty: "Faculty of Agriculture, Engineering & Natural Sciences",
    programName: "BSc in Microbiology",
    programCode: "33BSMB",
    duration: "3 years",
    minPoints: 25,
    admissionRequirements: [
      { subject: "Biology", level: "NSSCAS", minGrade: "D" },
      { subject: "Chemistry", level: "NSSCAS", minGrade: "D" },
      { subject: "Mathematics", level: "NSSCO", minGrade: "C" },
      { subject: "English", level: "NSSCO", minGrade: "C" },
    ],
    careerPossibilities: ["Microbiologist", "Lab Tech", "Research Assistant"],
    interestCategories: ["Health & Medicine", "Science & Research"],
  },
  {
    id: "unam-computing",
    institution: "UNAM",
    faculty: "Faculty of Agriculture, Engineering & Natural Sciences",
    programName: "Bachelor of Science in Computing",
    programCode: "33BSC",
    duration: "3 years",
    minPoints: 27,
    admissionRequirements: [
      { subject: "Mathematics", level: "NSSCAS", minGrade: "D" },
      { subject: "English", level: "NSSCO", minGrade: "C" },
    ],
    careerPossibilities: ["Software Developer", "Systems Analyst", "IT Consultant"],
    interestCategories: ["Technology & Computing"],
  },
  {
    id: "unam-data-science",
    institution: "UNAM",
    faculty: "Faculty of Agriculture, Engineering & Natural Sciences",
    programName: "Bachelor of Science in Data Science",
    programCode: "33BSDS",
    duration: "3 years",
    minPoints: 27,
    admissionRequirements: [
      { subject: "Mathematics", level: "NSSCAS", minGrade: "D" },
      { subject: "English", level: "NSSCO", minGrade: "C" },
    ],
    careerPossibilities: ["Data Scientist", "Machine Learning Engineer", "AI Specialist"],
    interestCategories: ["Technology & Computing", "Mathematics & Statistics"],
  },
  {
    id: "unam-statistics",
    institution: "UNAM",
    faculty: "Faculty of Agriculture, Engineering & Natural Sciences",
    programName: "Bachelor of Science in Statistics",
    programCode: "33BSST",
    duration: "3 years",
    minPoints: 27,
    admissionRequirements: [
      { subject: "Mathematics", level: "NSSCAS", minGrade: "D" },
      { subject: "English", level: "NSSCO", minGrade: "C" },
    ],
    careerPossibilities: ["Statistician", "Data Analyst", "Researcher"],
    interestCategories: ["Mathematics & Statistics", "Science & Research"],
  },
  {
    id: "unam-environmental-biology",
    institution: "UNAM",
    faculty: "Faculty of Agriculture, Engineering & Natural Sciences",
    programName: "Bachelor of Science in Environmental Biology (Honours)",
    programCode: "33BSEB",
    duration: "4 years",
    minPoints: 25,
    admissionRequirements: [
      { subject: "English", level: "NSSCO", minGrade: "D" },
      { subject: "Mathematics", level: "NSSCO", minGrade: "C" },
      { subject: "Biology", level: "NSSCO", minGrade: "C" },
      { subject: "Physical Science", level: "NSSCO", minGrade: "C" },
    ],
    careerPossibilities: ["Environmental Biologist", "Conservationist", "Researcher"],
    interestCategories: ["Agriculture & Environment", "Science & Research"],
  },

  // NUST Programs
  {
    id: "nust-computer-science",
    institution: "NUST",
    faculty: "Faculty of Computing and Informatics",
    programName: "Bachelor of Computer Science",
    programCode: "07BCMS",
    duration: "3 years",
    minPoints: 25,
    admissionRequirements: [
      { subject: "Mathematics", level: "NSSCO", minGrade: "D" },
      { subject: "English", level: "NSSCO", minGrade: "E" },
    ],
    careerPossibilities: ["Software Developer", "Network Specialist"],
    interestCategories: ["Technology & Computing"],
  },
  {
    id: "nust-cybersecurity",
    institution: "NUST",
    faculty: "Faculty of Computing and Informatics",
    programName: "Bachelor of Computer Science in Cyber Security",
    programCode: "07BCCY",
    duration: "3 years",
    minPoints: 25,
    admissionRequirements: [
      { subject: "Mathematics", level: "NSSCO", minGrade: "C" },
      { subject: "English", level: "NSSCO", minGrade: "E" },
    ],
    careerPossibilities: ["Cyber Analyst", "Security Developer"],
    interestCategories: ["Technology & Computing"],
  },
  {
    id: "nust-informatics",
    institution: "NUST",
    faculty: "Faculty of Computing and Informatics",
    programName: "Bachelor of Informatics",
    programCode: "07BAIT",
    duration: "3 years",
    minPoints: 25,
    admissionRequirements: [
      { subject: "Mathematics", level: "NSSCO", minGrade: "D" },
      { subject: "English", level: "NSSCO", minGrade: "E" },
    ],
    careerPossibilities: ["Web Analyst", "Systems Analyst"],
    interestCategories: ["Technology & Computing"],
  },
  {
    id: "nust-journalism",
    institution: "NUST",
    faculty: "Faculty of Computing and Informatics",
    programName: "Bachelor of Journalism and Media Technology",
    programCode: "07BJOU",
    duration: "3 years",
    minPoints: 25,
    admissionRequirements: [{ subject: "English", level: "NSSCO", minGrade: "D" }],
    careerPossibilities: [
      "Journalist",
      "Public Relations Practitioner",
      "Communication Specialist",
      "Media Designer",
      "Photographer/Videographer",
    ],
    interestCategories: ["Arts & Communication"],
  },
  {
    id: "nust-civil-engineering",
    institution: "NUST",
    faculty: "Faculty of Engineering and the Built Environment",
    programName: "Bachelor of Engineering in Civil Engineering",
    programCode: "08BCEN",
    duration: "4 years",
    minPoints: 37,
    admissionRequirements: [
      { subject: "Mathematics", level: "NSSCH", minGrade: "3" },
      { subject: "Physical Science", level: "NSSCH", minGrade: "3" },
      { subject: "Chemistry", level: "NSSCAS", minGrade: "D" },
    ],
    careerPossibilities: ["Civil Engineer", "Structural Engineer", "Transportation Engineer"],
    interestCategories: ["Engineering & Construction"],
  },
  {
    id: "nust-mechanical-engineering",
    institution: "NUST",
    faculty: "Faculty of Engineering and the Built Environment",
    programName: "Bachelor of Engineering in Mechanical Engineering",
    programCode: "08BEME",
    duration: "4 years",
    minPoints: 37,
    admissionRequirements: [
      { subject: "Mathematics", level: "NSSCH", minGrade: "3" },
      { subject: "Physical Science", level: "NSSCH", minGrade: "3" },
      { subject: "Chemistry", level: "NSSCAS", minGrade: "D" },
    ],
    careerPossibilities: ["Mechanical Engineer", "Reliability Engineer"],
    interestCategories: ["Engineering & Construction"],
  },
  {
    id: "nust-accounting",
    institution: "NUST",
    faculty: "Faculty of Commerce, Human Sciences and Education",
    programName: "Bachelor of Accounting",
    programCode: "07BGAC",
    duration: "3 years",
    minPoints: 30,
    admissionRequirements: [
      { subject: "English", level: "NSSCO", minGrade: "C" },
      { subject: "Mathematics", level: "NSSCO", minGrade: "C" },
    ],
    careerPossibilities: ["Accountant", "Internal Auditor", "Tax Assistant"],
    interestCategories: ["Business & Finance"],
  },
  {
    id: "nust-business-management",
    institution: "NUST",
    faculty: "Faculty of Commerce, Human Sciences and Education",
    programName: "Bachelor of Business Management",
    programCode: "07BBMN",
    duration: "3 years",
    minPoints: 25,
    admissionRequirements: [{ subject: "Mathematics", level: "NSSCO", minGrade: "D" }],
    careerPossibilities: ["Business Manager", "Entrepreneur", "Logistics Officer"],
    interestCategories: ["Business & Finance"],
  },
  {
    id: "nust-marketing",
    institution: "NUST",
    faculty: "Faculty of Commerce, Human Sciences and Education",
    programName: "Bachelor of Marketing",
    programCode: "07BMAK",
    duration: "3 years",
    minPoints: 25,
    admissionRequirements: [{ subject: "Mathematics", level: "NSSCO", minGrade: "D" }],
    careerPossibilities: ["Marketing Officer", "Sales Manager", "Brand Strategist"],
    interestCategories: ["Business & Finance"],
  },
  {
    id: "nust-medical-lab-sciences",
    institution: "NUST",
    faculty: "Faculty of Health, Natural Resources and Applied Sciences",
    programName: "Bachelor of Medical Laboratory Sciences",
    programCode: "08BMLS",
    duration: "4 years",
    minPoints: 24,
    admissionRequirements: [
      { subject: "Mathematics", level: "NSSCO", minGrade: "C" },
      { subject: "Biology", level: "NSSCO", minGrade: "C" },
      { subject: "Chemistry", level: "NSSCO", minGrade: "C" },
      { subject: "Physical Science", level: "NSSCO", minGrade: "C" },
    ],
    careerPossibilities: ["Medical Lab Scientist", "Food Analyst", "Water Quality Analyst"],
    interestCategories: ["Health & Medicine", "Science & Research"],
  },
  {
    id: "nust-agriculture",
    institution: "NUST",
    faculty: "Faculty of Health, Natural Resources and Applied Sciences",
    programName: "Bachelor of Science in Agriculture",
    programCode: "07BAGA",
    duration: "4 years",
    minPoints: 25,
    admissionRequirements: [
      { subject: "Mathematics", level: "NSSCO", minGrade: "E" },
      { subject: "Biology", level: "NSSCO", minGrade: "E" },
    ],
    careerPossibilities: ["Farm Manager", "Agricultural Research Officer", "Community Development Coordinator"],
    interestCategories: ["Agriculture & Environment"],
  },
  {
    id: "nust-natural-resource-management",
    institution: "NUST",
    faculty: "Faculty of Health, Natural Resources and Applied Sciences",
    programName: "Bachelor of Natural Resource Management",
    programCode: "07BNRS",
    duration: "4 years",
    minPoints: 25,
    admissionRequirements: [
      { subject: "English", level: "NSSCO", minGrade: "D" },
      { subject: "Mathematics", level: "NSSCO", minGrade: "D" },
      { subject: "Biology", level: "NSSCO", minGrade: "C" },
    ],
    careerPossibilities: ["Nature Conservationist", "Environmental Educator", "Tour Guide"],
    interestCategories: ["Agriculture & Environment"],
  },
]
